// automatically generated by the FlatBuffers compiler, do not modify

package com.sci4s.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Files extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_11_1(); }
  public static Files getRootAsFiles(ByteBuffer _bb) { return getRootAsFiles(_bb, new Files()); }
  public static Files getRootAsFiles(ByteBuffer _bb, Files obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Files __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String fileName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer fileNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer fileNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public byte fileBytes(int j) { int o = __offset(6); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int fileBytesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector fileBytesVector() { return fileBytesVector(new ByteVector()); }
  public ByteVector fileBytesVector(ByteVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer fileBytesAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer fileBytesInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createFiles(FlatBufferBuilder builder,
      int fileNameOffset,
      int fileBytesOffset) {
    builder.startTable(2);
    Files.addFileBytes(builder, fileBytesOffset);
    Files.addFileName(builder, fileNameOffset);
    return Files.endFiles(builder);
  }

  public static void startFiles(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addFileName(FlatBufferBuilder builder, int fileNameOffset) { builder.addOffset(0, fileNameOffset, 0); }
  public static void addFileBytes(FlatBufferBuilder builder, int fileBytesOffset) { builder.addOffset(1, fileBytesOffset, 0); }
  public static int createFileBytesVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createFileBytesVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startFileBytesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endFiles(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Files get(int j) { return get(new Files(), j); }
    public Files get(Files obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

