// automatically generated by the FlatBuffers compiler, do not modify

package com.sci4s.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RetMsg extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_11_1(); }
  public static RetMsg getRootAsRetMsg(ByteBuffer _bb) { return getRootAsRetMsg(_bb, new RetMsg()); }
  public static RetMsg getRootAsRetMsg(ByteBuffer _bb, RetMsg obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public RetMsg __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String errCode() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer errCodeAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer errCodeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String errMsg() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer errMsgAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer errMsgInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String results() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer resultsAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer resultsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createRetMsg(FlatBufferBuilder builder,
      int errCodeOffset,
      int errMsgOffset,
      int resultsOffset) {
    builder.startTable(3);
    RetMsg.addResults(builder, resultsOffset);
    RetMsg.addErrMsg(builder, errMsgOffset);
    RetMsg.addErrCode(builder, errCodeOffset);
    return RetMsg.endRetMsg(builder);
  }

  public static void startRetMsg(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addErrCode(FlatBufferBuilder builder, int errCodeOffset) { builder.addOffset(0, errCodeOffset, 0); }
  public static void addErrMsg(FlatBufferBuilder builder, int errMsgOffset) { builder.addOffset(1, errMsgOffset, 0); }
  public static void addResults(FlatBufferBuilder builder, int resultsOffset) { builder.addOffset(2, resultsOffset, 0); }
  public static int endRetMsg(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public RetMsg get(int j) { return get(new RetMsg(), j); }
    public RetMsg get(RetMsg obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

